### ISSUE TITLE
Decimals are not calculated 

### ISSUE THREAD

**Issue by bhishma** [tamim9/smart-calculator#1]
Really nice UI. Sleek.
Decimals are ignored in multiplication.
In division, it's off by factor of 10

**Comment by sr-tamim** [comment]
**Thanks** a lot for your comment. I'll work on your mentioned issues.

### Have you checked my other calculator?

- If not, visit [here](https://github.com/tamim9/scientific-calculator)
- If yes, write your review [here](https://github.com/tamim9/scientific-calculator/issues)

**Comment by sr-tamim** [comment]
### Issue solved by [this commit](https://github.com/tamim9/smart-calculator/commit/3ec7f3dd413f5f3ff9e39869566acc0c194ac754)

**Thanks** to @bhishma for opening this issue.

**Comment by bhishma** [comment]
Thanks. Still one more issue.
If you have decimal in first number and no decimals in second, it fails to properly calculate a sum. 
Other operations look good.
Try 1.5+2

**Comment by sr-tamim** [comment]
### Thanks for finding another issue.
I've found the **bug** responsible for this issue. Actually I wrote `'0'` instead of `0`, that's why JavaScript calculated it as a **string** (not a **number**).
I've corrected it & hope that issue will be vanished!
